lib/fog/aws/parsers/auto_scaling/describe_launch_configurations.rb
=> [AWS|Autoscaling] Add missing ebs attributes to describe_launch_configurations

lib/fog/aws/models/auto_scaling/activities.rb, lib/fog/aws/models/auto_scaling/group.rb
The AutoScaling#Group.activities method was doing something very strange - loading the collection rather than letting it load itself.
The activities model itself was also doing something very strange since it was assuming that all the arguments passed to it were filters, whereas we need to pass in the service (and since filters are dumped straight into the request parameters this caused an exception in the request signing code).
I'm not super familiar with the Fog::Collection stuff, but I think this is closer to what it should do (and does actually work).
=> fix autoscaling activities collection setup

lib/fog/aws/parsers/auto_scaling/describe_launch_configurations.rb, tests/requests/auto_scaling/auto_scaling_tests.rb
Let me know if I should update any part to conform with coding standards etc.
=> Add PlacementTenancy to launch configuration parser and test case

lib/fog/aws/storage.rb
We're getting ```"undefined method `captures' for nil:NilClass"``` when sending requests with the wrong region. This PR updates the error parsing to handle the case where a new region isn't specified (the comment above this line suggests only some errors explicitly provide it).
=> Allow for AWS errors not specifying region

lib/fog/aws/storage.rb
This PR attempts to address the following issue:
**TypeError - no implicit conversion of nil into String**
https://github.com/fog/fog/issues/3300
Previous PR's and commits have attempted to provide a solution:
- https://github.com/fog/fog/commit/46a7a47d043169e52f4ab6ee676613cad08b0690
- https://github.com/fog/fog-aws/pull/2
Taking a look at https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb
It seems like if `options[:endpoint]` is set then `@region` will be nil when passed into `Fog::AWS::SignatureV4.new( @aws_access_key_id, @aws_secret_access_key, @region, 's3')`
ref: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L467
This PR suggests defaulting `@region` at the outset to avoid the issue of it being nil
Is there a reason `@region` should be nil if …
=> BUGFIX: When fog_credentials endpoint is set @region defaults to nil

lib/fog/aws/requests/dns/change_resource_record_sets.rb, lib/fog/aws/requests/dns/get_hosted_zone.rb, lib/fog/aws/requests/dns/list_resource_record_sets.rb
This PR add `idempotent` attribute to underlying request calls to retry in case AWS throws a 400 error.
Affected API calls:
- ChangeResourceRecordSetsRequest
- GetHostedZone
- ListResourceRecordSets
=> Add idempotent excon option to some route53 API calls

lib/fog/aws/signaturev4.rb, tests/signaturev4_tests.rb
This fixes fog/fog#3416 for me
=> Fix v4 signature when path has repeated slashes in the middle

lib/fog/aws/requests/dynamodb/scan.rb
'AttributeValueList' needs to be an array of 'AttributeValue' and not Hash.
=> Fix for ScanFilter parameters

lib/fog/aws/storage.rb
Ported from fog/fog#3140.
This allows users to pass `bucket_cname: true` and have the url be generated as per http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingCustomURLs
If this is missing tests, documentation, please let me know where and how it should be done. I couldn't find out much from the contributing guidelines. Thanks
=> Add support for cname buckets

lib/fog/aws/requests/storage/post_object_hidden_fields.rb
Hi,
` post_object_hidden_fields ` doesn't make any external call, can be used as Mock method. Tell me if there a more elegant way to do this instead of copy & paste.
=> Mock method for AWS S3 post_object_hidden_fields 

lib/fog/aws/storage.rb
* The query hash expects that all keys are strings. If the query hash
has both string and symbol keys the `signature_v2` method raises an
exception
* The query hash is often the leftover keys that have not been
extracted from the initial request.
* The conversion of sym -> string is done elsewhere for other parameters
* Makes the request more robust in general.
=> Stringify keys for query parameters

lib/fog/aws/requests/compute/describe_availability_zones.rb
Added a couple lines so that the Mock class knows about eu-central-1a and eu-central-1b.
=> eu-central missing from Fog::Compute::AWS::Mock

lib/fog/aws/models/compute/servers.rb
Issue with provisioning EC2 instances where security group's SSH inbound 0.0.0.0/0 permission is not at index 0.
**Repro:**
1. Create security group "Foo" with rule: Allow inbound port 22 from your IP.
1. Start an instance with connection.servers.bootstrap, groups: ["Foo"]
1. Observe Foo. Notice that fog-aws adds the rule SSH inbound 0.0.0.0/0, and it's at index 1.
1. Start another instance with the same arguments.
1. Error is `gems/excon-0.44.4/lib/excon/middlewares/expects.rb:6:in `response_call': Duplicate => the specified rule \"peer: 0.0.0.0/0, TCP, from port: 22, to port: 22, ALLOW\" already exists (Fog::Compute::AWS::Error)` from [fog/aws/models/compute/servers.rb:205](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/servers.rb#L205)
This fixes it by checking …
=> Fix EC2 security groups where SSH inbound rule isn't first

lib/fog/aws/requests/dns/change_resource_record_sets.rb, tests/requests/dns/change_resource_record_sets_tests.rb
Fixes a an error `undefined method `last' for {"eu-west-1"=>"Z3NF1Z3NOM5OY2"}:Hash` when using the `change_resource_record_sets` method.
Also added support for the new eu-central-1 region
=> Resource record sets bug fix + support eu-central-1 

lib/fog/aws/storage.rb
1e799c59187702650253000f80bed67e422acc5f expects that params[:query] is always defined, and also introduced another bug that reassigned params incorrectly
=> Fix for `undefined method `map' for nil:NilClass`

lib/fog/aws/requests/rds/create_db_snapshot.rb, lib/fog/aws/requests/rds/delete_db_instance.rb, tests/models/rds/server_tests.rb
* `InvalidParameterCombination => FinalDBSnapshotIdentifier can not be specified when deleting a replica instance`
=> [rds] prevent final snapshot on replicas

lib/fog/aws/models/storage/file.rb
Came across this today. Hopefully this change makes the method a little easier to read.
=> Remove assignment within conditional in File#body

lib/fog/aws/requests/rds/describe_db_instances.rb
* and fix variable shadow warning
=> create db instance in the correct region

lib/fog/aws/parsers/compute/describe_spot_price_history.rb, lib/fog/aws/requests/compute/describe_spot_price_history.rb, tests/requests/compute/spot_price_history_tests.rb
Hi folks,
I noticed I couldn't pass some parameters to EC2 DescribeSpotPriceHistory action, so I changed the parameters handling for this function. Without my changes, I was unable to find a way to properly filter the spot prices history as is described in the API documentation.
Thanks,
=> Handle missing parameters in describe_spot_price_history request

lib/fog/aws/storage.rb
=> Fix blank content-encoding when none is supplied

lib/fog/aws.rb
On the last PR i left some requires that could been using `autoload` to improve the performance over the issue with fog/fog#3430.
=> Move more requires to autoload

lib/fog/aws/models/compute/flavors.rb
AWS has released [Dense-storage Instances](https://aws.amazon.com/blogs/aws/next-generation-of-dense-storage-instances-for-ec2/) for EC2.
Modify ` lib/fog/aws/models/compute/flavors.rb` for adding d2 instance types.
=> adding support for d2 instance type

lib/fog/aws/requests/elb/create_load_balancer.rb
When mocking, the way it was getting the region would 
always fail if you weren't passing in availability zones. 
Fixed so it finds the region for subnet_ids passed in.
=> Fix mock VPC ELB creation in regions other than us-east-1

lib/fog/aws/parsers/compute/describe_reserved_instances.rb
Simple change adding one field to the reserved instance parser. Field is present on response per: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeReservedInstances.html
=> Adding instanceTenancy to reserved instance parser.

lib/fog/aws/iam.rb
This should improve support for GovCloud, which requires requests to be scoped to its own region.
Fixes https://github.com/fog/fog-aws/issues/100.
=> Allow the IAM constructor to accept a region

lib/fog/aws/storage.rb
=> Another attempt to solve content-encoding header issues

lib/fog/aws/iam.rb, lib/fog/aws/models/iam/policies.rb, lib/fog/aws/models/iam/users.rb, lib/fog/aws/requests/iam/create_user.rb, lib/fog/aws/requests/iam/get_user.rb, tests/models/iam/users_tests.rb, tests/requests/iam/helper.rb, tests/requests/iam/user_tests.rb
=> support iam/get_user without username

lib/fog/aws/models/elb/load_balancer.rb, lib/fog/aws/models/elb/policies.rb, lib/fog/aws/models/elb/policy.rb
* there is no need to inject data from the load balancer model when
an index request exists that maps directly
=> make elb/policies collection standalone

lib/fog/aws/signaturev4.rb, tests/signaturev4_tests.rb
S3 implements signature v4 different from other services - it doesn't canonicalize the path
With this pull requests I can store keys such as `//fred//..//tes!$%&t`
See also #113
=> Fix S3 signature v4 signing

lib/fog/aws/requests/compute/create_vpc.rb, tests/requests/compute/vpc_tests.rb
This difference in method arity was spuriouly breaking tests that have
nothing to do with those options being passed (InstanceTenancy in my
case).
=> Make Mock create_vpc method arity match Real

lib/fog/aws/models/dns/zones.rb
If the hash key is string it won't get applied in list_hosted_zones.
=> list_hosted_zones expects that options to be hash with symbol as key

lib/fog/aws/requests/dns/change_resource_record_sets.rb, tests/requests/dns/change_resource_record_sets_tests.rb
Without this, calling `record.destroy` on a record that has geolocation set will cause an exception with:
```
Fog::DNS::AWS::Error: MalformedInput => Unexpected complex element termination
```
=> The :geo_location attribute needs to be xml formatted before calling aws

lib/fog/aws/parsers/compute/describe_vpcs.rb
Missing attribute documented in https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Vpc.html
=> Adds isDefault to parser for describe_vpcs

lib/fog/aws/requests/dns/change_resource_record_sets.rb, tests/requests/dns/change_resource_record_sets_tests.rb
This method was broken up into two in 0.7.0, but the big one was changed to a class method. The XML body string, however, still interpolated `@version` to set the XML namespace, and ended up being `https://route53.amazonaws.com/doc//`, which causes AWS to refuse to parse the XML, returning:
Cannot find the declaration of element 'ChangeResourceRecordSetsRequest'
I was unable to change any RRs until I downgraded to 0.6.0.
I added an `xmlns` check to the test, but it's just a hardcoded string. Maybe an enterprising person could move all the default versions for all AWS services to constants make sure that every `xmlns` is tested somewhere. (Better yet, don't build XML by concatenating strings?) But I'd prefer to just fix this at the moment.
=> Fix broken xmlns in DNS requests

lib/fog/aws/storage.rb
The S3 docs claim that you should set the content-encoding to aws-chunked
for a streaming upload. This however results in S3 serving files with a blank
content-encoding header. After discussion with AWS support, it appears
that setting the content-encoding to aws-chunked isn't actually necessary
since S3 can infer this from other headers present in the request
See #130, #106 , #75
=> Fix blank content-encoding headers

lib/fog/aws/storage.rb
Signed-off-by: Aakash Shah <ashah@pivotal.io>
Scenario:
- Our S3 bucket is in west
- We set path_style to true when opening a connection. This results in a url such as <bucket>.s3.amazonaws.com versus s3.amazonaws.com/<bucket>
- We have also set 'https://s3.amazonaws.com' for our endpoint
- It appears that when fog creates the connection to S3, S3 responds with a redirect asking it to use <bucket>.s3.amazonaws.com as the endpoint for any subsequent communication.
- As fog parses this redirect request [1], it doesn't appear to respect path_style being true and asserts equality of the endpoint against s3.amazonaws.com to determine the region. Unfortunately, that's not what the endpoint looks like with path_style being true. Fog blows up as it then believes the endpoint to be a non-US …
=> Use regex instead of string matching to support redirect correctly when path_style is set to true

lib/fog/aws/requests/storage/put_bucket.rb, tests/requests/storage/bucket_tests.rb
In the default region (us-east-1), put_bucket will return an existing
bucket, rather than throw a BucketAlreadyOwnedByYou error. Changed the
mock to reflect this behavior.
This fixes https://github.com/fog/fog-aws/issues/172
=> Mocked put_bucket no longer clobbers existing bucket

lib/fog/aws.rb
It looks like the GovCloud region was left off  the enumerated set of region names.
It's a bit difficult to parse Amazon's documentation, but we believe 'us-gov-west-1' is the only GovCloud region:
http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html
We discovered this through mitchellh/vagrant-aws, which uses this library to validate Vagrant parameters when building ec2 instances.
=> Add GovCloud region name to validation set.

lib/fog/aws/requests/storage/get_object.rb
Minor tweak to Mock#get_object to make the arguments yielded to a given block more closely match the arguments that are passed by Excon in the Real case.
Tests seem to be broken on master right now :crying_cat_face:
=> Yield arguments to Mock#get_object block more similar to Excon

lib/fog/aws/requests/storage/get_object.rb
The idempotent option can be problematic when calling get_object with a streaming block since Excon automatically retries the entire request from the beginning when something goes wrong, without making it clear that it's doing so. This can result in lots of issues, including data corruption. In order to prevent this, I'd like to propose that we disable the idempotent option whenever a streaming block is provided to get_object.
Original Issue: https://github.com/fog/fog-aws/issues/181
=> Disable idempotent option when block is passed to get_object

lib/fog/aws/requests/compute/describe_instances.rb, lib/fog/aws/requests/compute/start_instances.rb, lib/fog/aws/requests/compute/stop_instances.rb, tests/models/compute/server_tests.rb, tests/requests/compute/instance_tests.rb
* `Server#stop` was returning the wrong state
* `#stop_instances` and `#start_instances` mocks did not include the `requestId`
* tests for all of the above
=> mock instance stop and start properly

lib/fog/aws/sts.rb
STS is now available in all regions. (although somewhat oddly you have to manually enable each region other than us-east-1 from the AWS console - see https://blogs.aws.amazon.com/security/post/Tx3CYWU11LY2GLB/AWS-Security-Token-Service-Is-Now-Available-in-Every-AWS-Region )
=> Allow region to be set for STS

lib/fog/aws/storage.rb
s3 endpoint for `cn-north-1` is different. Tested using my account on aws china.
=> add cn support for s3

lib/fog/aws/models/elasticache/cluster.rb, lib/fog/aws/parsers/elasticache/cache_cluster_parser.rb, lib/fog/aws/requests/elasticache/create_cache_cluster.rb
Not sure if this is a bug or just Fog not keeping pace with the AWS API but it looks like ElastiCache security groups took on a new format and are now available under a key called `SecurityGroups`. This PR adds parsing for that key without dropping parsing for the old one. Let me know what you think.
Note that I didn't add any unit tests because there did not appear to be a test framework already set up for ElastiCache in Fog and I don't really have the cycles (or the knowledge, really) to create one just to test this one fix.
=> Cache cluster security group parser

lib/fog/aws/requests/storage/put_object.rb
#196 
Document options for [the three ways of S3 server-side encryption](http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html).
=> Document options for S3 server-side encryption

lib/fog/aws/compute.rb, tests/requests/compute/instance_tests.rb
this comparison works fine where there is just a string or single tag,
where there is an array of tags this comparison breaks fails.
So instead we must cast to an array and then do a comparison by an
inclusion of a a value in an array
=> filters on tags can pass an array

Gemfile
The mime-types gem is needed to run the tests.
=> Add mime-types to test section in Gemfile

lib/fog/aws/storage.rb
I've found that when idempotent PUT requests are retried, the bodies of the requests are empty because the `self.finished` attribute of the `S3Streamer` is evaluating to `true`. If the attribute to reset to `false` when `#rewind` is called, the body of the request is sent on retries.
=> Reset 'finished' when rewinding S3Streamer

lib/fog/aws/parsers/storage/get_bucket_lifecycle.rb, lib/fog/aws/requests/storage/put_bucket_lifecycle.rb, tests/requests/storage/bucket_tests.rb
S3 has lifecycle policies for versioned objects that fog didn't support. This supports writing & parsing lifecycle specs for non-current versions of objects.
An example:
```ruby
require 'fog/aws'
s3 = Fog::Storage[:aws]
b = s3.directories.get('cmtestlifecycle')
lifecycle = { 'Rules' => [ { 'ID' => 'one-month-retention', 'Enabled' => true, 'NoncurrentVersionExpiration' => {'NoncurrentDays' => 30} } ] }
s3.put_bucket_lifecycle b.key, lifecycle
res = s3.get_bucket_lifecycle(b.key)
```
=> Support NoncurrentVersion[Expiration,Transition] for s3 lifecycle.

lib/fog/aws/models/storage/directory.rb, tests/models/storage/directory_tests.rb
As detailed in #208, buckets without location constraints should default to the AWS default region and not that used by the current connection.
=> When not specified, region for a bucket should be DEFAULT_REGION.

lib/fog/aws/requests/dynamodb/batch_get_item.rb, lib/fog/aws/requests/dynamodb/batch_write_item.rb, lib/fog/aws/requests/dynamodb/create_table.rb, lib/fog/aws/requests/dynamodb/delete_item.rb, lib/fog/aws/requests/dynamodb/delete_table.rb, lib/fog/aws/requests/dynamodb/describe_table.rb, lib/fog/aws/requests/dynamodb/get_item.rb, lib/fog/aws/requests/dynamodb/list_tables.rb, lib/fog/aws/requests/dynamodb/put_item.rb, lib/fog/aws/requests/dynamodb/query.rb, lib/fog/aws/requests/dynamodb/scan.rb, lib/fog/aws/requests/dynamodb/update_item.rb, lib/fog/aws/requests/dynamodb/update_table.rb, tests/requests/dynamodb/item_tests.rb
The `20111205` API version is deprecated, and doesn't provide many of the features the latest version offers, such as the [conditional parameters](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.html).
=> Update dynamodb to use the latest API version

lib/fog/aws/models/compute/security_group.rb
Security Group perms of FromPort 0 and ToPort -1
Fix generation of the FromPort and ToPort paramters when authorizing or revoking permissions on a security group.
Using `min` and `max` to get the parts of a range can somtimes return nil, using `begin` and `end` will always return the actual values the range was created with
Example: `(0..-1).min` is nil and `(0..-1).max` is also nil
Error message from AWS would be:
Invalid value 'Must specify both from and to ports with ICMP.' for portRange
=> Security Group perms of FromPort 0 and ToPort -1

lib/fog/aws/auto_scaling.rb, lib/fog/aws/models/auto_scaling/group.rb, lib/fog/aws/requests/auto_scaling/attach_instances.rb, lib/fog/aws/requests/auto_scaling/detach_instances.rb, lib/fog/aws/version.rb, tests/requests/auto_scaling/auto_scaling_tests.rb
Ran this against a live amazon account and this did the expected. 
Amazon doc links inline in the commit.
=> autoscaler attach/detatch

lib/fog/aws/parsers/cloud_formation/describe_stacks.rb
The presence of tags on CloudFormation stacks would break the previous implementation due to the unexpected `<member>` elements.
Fixes #240.
=> Add support for CloudFormation stack tags.

lib/fog/aws/parsers/cloud_watch/describe_alarms.rb
If someone else is willing to do the work to create a CloudWatch unit test framework I will write a test for this change. ;-)
=> Parse CloudWatch alarm actions as arrays instead of strings

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
Doing a `compute.servers` should work according as expected in mock mode when using it with an iam role (ie `use_iam_profile`), but currently the credentials_fetcher is making real requests. This just mocks the api keys that it would get in the real mode.
=> do not make requests if mocked.

lib/fog/aws/requests/storage/put_bucket.rb
- Non us-regions are not supported for mocks. Added message
=> Add log warning message about when not on us-region

lib/fog/aws/parsers/storage/get_bucket.rb
Fog aws fails if API response contains empty ETag tags. It may cause when working with S3 clones (like minio in my case), that not provides ETags in their API answer.
=> Fix for empty ETag values

lib/fog/aws/models/dns/records.rb
I want to change to case-insensitive comparison to allow this use case:
```
"server1.example.com".casecmp("SERVER1.example.com") == 0
```
=> Allow case-insensitive record comparison

lib/fog/aws/parsers/auto_scaling/describe_launch_configurations.rb
This value is always treated as nil in current master
As in a similar prior pull, I'm not sure where/if to add tests: https://github.com/fog/fog-aws/pull/29
=> Parse EbsOptimized parameter in launch configuration description

lib/fog/aws/requests/dns/change_resource_record_sets.rb
See https://forums.aws.amazon.com/message.jspa?messageID=612414
Setting up DNS ALIAS records for the newer (and now default) dualstack DNS records without the correct hosted zone ID will result in odd things happening, typically only one IP address being returned for an ELB.
=> AWS DNS - support newer DNS hosted zone IDs for dualstack ELBs

lib/fog/aws/glacier.rb, lib/fog/aws/models/storage/file.rb, lib/fog/aws/requests/glacier/create_archive.rb, lib/fog/aws/requests/glacier/upload_part.rb, lib/fog/aws/requests/sqs/send_message.rb, lib/fog/aws/requests/storage/delete_multiple_objects.rb, lib/fog/aws/requests/storage/post_object_restore.rb, lib/fog/aws/requests/storage/put_bucket_acl.rb, lib/fog/aws/requests/storage/put_bucket_cors.rb, lib/fog/aws/requests/storage/put_bucket_lifecycle.rb, lib/fog/aws/requests/storage/put_bucket_notification.rb, lib/fog/aws/requests/storage/put_bucket_tagging.rb, lib/fog/aws/requests/storage/put_object_acl.rb, lib/fog/aws/requests/storage/shared_mock_methods.rb, lib/fog/aws/signaturev4.rb, lib/fog/aws/storage.rb, tests/models/storage/file_tests.rb, tests/requests/glacier/tree_hash_tests.rb
The Digest class has some thread safety issues and gives runtime error 
Digest::Base cannot be directly inherited in Ruby #261
ruby/ruby@c02fa39
aws/aws-sdk-ruby#525
aws/aws-sdk-ruby#529
=> Replaces usage of Digest with OpenSSL::Digest 

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
Default to using the region /cc @silvermy
=> add default region to use_iam_profile

lib/fog/aws/requests/rds/copy_db_snapshot.rb, tests/requests/rds/db_snapshot_tests.rb, tests/requests/rds/helper.rb
Some RDS tests were failing due to a bad mock returned with copy_db_snapshot, and a couple of old/incorrect formats for said snapshots.
=> RDS test fixes

lib/fog/aws/models/rds/cluster.rb
>> `connection.clusters.create(......, :db_subnet_group=>'subnetgroup-18')`
_Error thrown is_ :- 
>>` Fog::AWS::RDS::Error: InvalidParameterCombination => Database is in vpc-c046a0a9, but Ec2 Security Group sg-5831ce31 is in vpc-91a95df8`
- As the name of `SubnetGroup` at create_db_cluster.rb is DBSubnetGroupName
- Mapping at cluster.rb is made to **DBSubnetGroupName**
=> Change DBSubnetGroup to DBSubnetGroupName model cluster while creation

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
This adds support for ECS task container credentials/roles.
Docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
aws-sdk PR: https://github.com/aws/aws-sdk-ruby/pull/1243
I used the same algorithm as aws-sdk for choosing when to use the ECS creds.  I don't love the `options[:metadata_connection]` but we have to connect to a different host to get the region when using ECS creds.
=> ECS container credentials

lib/fog/aws/models/storage/file.rb
Fixes https://github.com/fog/fog/issues/3899
@geemus did not write a test for this, spent a bit of time dabbling with shindo(nt) and have a real (non mock) test but couldn't get AWS auth params passed to run the test. Have tested manually with 0b, 5242879b and 10m files and all upload correctly with multipart being set on file size >= multipart_chunk.
=> Skip multipart if body size is less than chunk. 

lib/fog/aws/cloud_formation.rb, lib/fog/aws/parsers/cloud_formation/create_change_set.rb, lib/fog/aws/parsers/cloud_formation/describe_account_limits.rb, lib/fog/aws/parsers/cloud_formation/describe_change_set.rb, lib/fog/aws/parsers/cloud_formation/describe_stack_resource.rb, lib/fog/aws/parsers/cloud_formation/estimate_template_cost.rb, lib/fog/aws/parsers/cloud_formation/get_stack_policy.rb, lib/fog/aws/parsers/cloud_formation/get_template_summary.rb, lib/fog/aws/parsers/cloud_formation/list_change_sets.rb, lib/fog/aws/requests/cloud_formation/cancel_update_stack.rb, lib/fog/aws/requests/cloud_formation/continue_update_rollback.rb, lib/fog/aws/requests/cloud_formation/create_change_set.rb, lib/fog/aws/requests/cloud_formation/create_stack.rb, lib/fog/aws/requests/cloud_formation/delete_change_set.rb, lib/fog/aws/requests/cloud_formation/describe_account_limits.rb, lib/fog/aws/requests/cloud_formation/describe_change_set.rb, lib/fog/aws/requests/cloud_formation/describe_stack_resource.rb, lib/fog/aws/requests/cloud_formation/estimate_template_cost.rb, lib/fog/aws/requests/cloud_formation/execute_change_set.rb, lib/fog/aws/requests/cloud_formation/get_stack_policy.rb, lib/fog/aws/requests/cloud_formation/get_template_summary.rb, lib/fog/aws/requests/cloud_formation/list_change_sets.rb, lib/fog/aws/requests/cloud_formation/set_stack_policy.rb, lib/fog/aws/requests/cloud_formation/signal_resource.rb
This adds all the missing commands from the latest aws cloud formation including support for change sets, stack policy and other missing cloud formation calls.  This is mostly additional code it would be great if we can get this in next version.
=> Cloud Formation: support for change sets, stack policy and other missing calls.  

lib/fog/aws/models/compute/vpc.rb, lib/fog/aws/parsers/compute/describe_vpcs.rb
Add `is_default` attribute in vpc model
We have this attribute in aws api response and we saved this attribute in response parser as a string but not with a real attribute
=> Add attribute is_default in vpc

lib/fog/aws/compute.rb, lib/fog/aws/models/compute/security_group.rb, lib/fog/aws/requests/compute/authorize_security_group_egress.rb, lib/fog/aws/requests/compute/revoke_security_group_egress.rb, tests/models/compute/security_group_tests.rb
Hi guys !
Just a little PR to add gestion of egress security group rules (authorize / revoke).
For ensure retro-compatibility I add an optional parameters that indicate if the rules is ingress or egress, but then it's less better abstraction of AWS API. WDYT about this ?
I'm not sure that is the best way for implement this functionality, I will be listening you, feel free to tell me if I'm doing something wrong.
Thanks.
=> Add gestion of egress security group rules

lib/fog/aws/requests/storage/delete_multiple_objects.rb, tests/requests/storage/object_tests.rb
Hello!
I was debugging https://github.com/backup/backup/issues/670 and i found out that fog-aws' `#delete_multiple_objects` does not work with UTF-8 file names.
The problem is in the 'Content-Length' header, `String#length` is not the right method to find UTF-8 strings size:
```
> "fØg_öbjèct".length
=> 10
> "fØg_öbjèct".bytesize
=> 13
```
Please review the test, it not very clear to me if that's enough (https://github.com/fog/fog-aws/issues/311)
=> fix S3 #delete_multiple_objects for UTF-8 names

lib/fog/aws/requests/sts/assume_role.rb
Add `Fog::AWS::STS.Mock#assume_role`. The method returns a `Excon::Response` instance mocking the following fields:
* `Arn`
* `AssumedRoleId`   
* `AccessKeyId`     
* `SecretAccessKey` 
* `SessionToken`    
* `Expiration`     
* `RequestId`
=> Add `Fog::AWS::STS.Mock#assume_role`

.travis.yml, Gemfile, tests/helper.rb
Running the tests by `bundle exec shindo tests/requests/sqs` and it shows two warnings.
First is
```
W, [2016-11-19T12:08:19.789039 #2878]  WARN -- :
This usage of the Code Climate Test Reporter is now deprecated. Since version
1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
run the provided `codeclimate-test-reporter` binary separately to report your
results to Code Climate.
```
The second one is
```
SimpleCov failed to recognize the test framework and/or suite used. Please specify manually using SimpleCov.command_name 'Unit Tests'.
```
I follow the usage mentioned in [ruby-test-reporter Upgrading from pre-1.0 Versions](https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions)
I execute `bundle exec shined tests/` again and confirm …
=> Fix warnings in running tests

lib/fog/aws/models/compute/image.rb, lib/fog/aws/models/compute/images.rb, lib/fog/aws/parsers/compute/describe_images.rb, lib/fog/aws/requests/compute/describe_images.rb, tests/requests/compute/image_tests.rb
Have added creationDate and enaSupport members to image so as to know the images created date and if they support enhanced networking.
See: 
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Image.html
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html
* https://github.com/fog/fog-aws/blob/7e5e6ff/lib/fog/aws/parsers/compute/describe_images.rb
Fixes: https://github.com/fog/fog-aws/issues/320
=> Add creation date and enhanced networking support for images

lib/fog/aws/sqs.rb
Trying to create FIFO queue following [the document](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html), the error occurs (ommited some lines):
```
/path/to/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/expects.rb:7:in `response_call': Expected(200) <=> Actual(400 Bad Request) (Excon::Error::BadRequest)
InvalidParameterValue Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length
```
The script is
```ruby
require 'fog/aws'
sqs = Fog::AWS::SQS.new region: "us-west-2"
sqs.create_queue(name="FifoQueue.fifo", {"Attribute.1.Name" => "FifoQueue" , "Attribute.1.Value" => "true"})
```
The error says a queue name can't include '.' but fifo queue needs the '.fifo' suffix.
The version of query api fog-awe uses in …
=> Fix the bug that can't create fifo queue in SQS.

lib/fog/aws/models/compute/flavors.rb
Correctly set r3.large to not have EBS optimization available.
Remove a couple spurious spaces.
=> Add new t2.xlarge, t2.2xlarge and r4 class instances.

lib/fog/aws/credential_fetcher.rb
We would like to handle temporary issues with credential retrieval from AWS metadata server (usually running at 169.254.169.254) in a bit more resilient way. One possibility to achieve this is to mark the calls as idempotent, which means excon will retry them up to 3 times.
We are proposing the changes to the code in this PR. Please let us know if you have any comments or suggestions for improvement.
=> credential_fetcher: Mark AWS metadata calls as idempotent

lib/fog/aws/requests/dns/change_resource_record_sets.rb
There are many new regions, this is the complete list as of today.  Very annoying that we should have to maintain this arbitrary mapping, and annoying that Amazon states in their docs it is auto-assigned in the AWS console yet not in the API.
=> Updated ELB Dual Stack hosted zone DNS records

lib/fog/aws/auto_scaling.rb, lib/fog/aws/models/auto_scaling/group.rb, lib/fog/aws/requests/auto_scaling/attach_load_balancer_target_groups.rb, lib/fog/aws/requests/auto_scaling/detach_load_balancer_target_groups.rb, tests/requests/auto_scaling/auto_scaling_tests.rb
This is in reference to https://github.com/fog/fog-aws/issues/328
Unfortunately I will not have time to implement support for managing
the actual ALBs and all that is reated to them.
=> Added support for attaching auto scaling groups to target groups

.travis.yml, gemfiles/Gemfile-ruby-1.9, gemfiles/Gemfile-ruby-2.0
Nokogiri >= 1.7 requires Ruby 2.1 or higher.
=> Pin nokogiri gem for Ruby 1.9 and Ruby 2.0

lib/fog/aws/parsers/compute/describe_reserved_instances.rb, lib/fog/aws/requests/compute/describe_reserved_instances.rb
To get access to the new Region reserved instances, I needed to add 'scope' to the parser, and specify a newer API version when creating the AWS connection, i.e.
```
AWS = Fog::Compute.new({
provider: 'AWS',
version: '2016-11-15',
...
})
```
=> Fix parsing of the Reserved Instance 'recurringCharge' field and add 'scope' field

lib/fog/aws/auto_scaling.rb, lib/fog/aws/requests/auto_scaling/create_auto_scaling_group.rb, tests/requests/auto_scaling/auto_scaling_tests.rb, tests/requests/auto_scaling/model_tests.rb, tests/requests/auto_scaling/tag_tests.rb
* Restore passing live tests
* Fix setting tags on #create_auto_scaling_group
=> Fixes / improvements for AutoScaling

lib/fog/aws/requests/storage/delete_bucket_policy.rb, lib/fog/aws/requests/storage/get_bucket_object_versions.rb, lib/fog/aws/requests/storage/get_object.rb, tests/requests/storage/object_tests.rb, tests/requests/storage/versioning_tests.rb
Opening this PR for some early feedback and discussion. Originally I raised the issue (#341) under my other account (@ac-astuartkregor).
It occurred to me that some folks might be using the existing functionality in their tests. Therefore this PR could cause breakages if they are already reliant on the response status being set, rather than having to rescue the exception in their code.
I have looked at the storage requests and found any instances where a mock was setting a status code but not raising an Excon::Error of the appropriate flavour. The changes made have been verified against the actual result received when Fog is not in mock mode. Extra tests have been added to verify the success and failure cases of the various requests, in particular the `get_object` and `head_object` …
=> Fog mock accuracy, fixes #341

lib/fog/aws/credential_fetcher.rb
Hey, thanks for the awesome work on this gem 👍 
This PR avoids an extra fetch if region is specified.
The main benefit isn't performance, but rather permissions. For containers, AWS recommends blocking the instance metadata host (with `iptables`) so containers running on Amazon ECS don't have access to the underlying EC2 instance credentials.
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
=> Skip call to instance metadata host if region is specified

lib/fog/aws/models/compute/flavors.rb
This adds the [p2 instance types](https://aws.amazon.com/ec2/instance-types/p2/).  These are gpu-based, but there wasn't a key for specifying the number of GPUs, so I followed the existing pattern.
=> Add p2 instance types

lib/fog/aws/models/storage/file.rb, tests/models/storage/file_tests.rb
As described in https://github.com/fog/fog-aws/issues/364
=> Handle multipart upload of empty files

lib/fog/aws/credential_fetcher.rb
Pass `region` to credential refresh if specified. Otherwise, Fog tries to call instance metadata host. More context in #360.
=> Fixed credential refresh when instance metadata host is inaccessible

lib/fog-aws.rb
Reduce confusion by allowing the gem to be required via a file that
matches the gem name.
References https://github.com/fog/fog/issues/3959
=> Add a top-level require that matches the gem name

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
The change introduced in #252 does not actually prevent HTTP requests
from being made because of a missing early return statement.
=> Fix AWS credential mocking

lib/fog/aws/parsers/compute/describe_reserved_instances_offerings.rb, lib/fog/aws/requests/compute/describe_reserved_instances_offerings.rb
A little PR for :
- Add `MaxResults` and `NextToken` filter to describe_reserved_instances_offerings.
- Update the serializer for adding `nextToken` in the result payload.
=> Add MaxResults filter to describe reserved instances offerings

lib/fog/aws/parsers/compute/describe_images.rb, tests/parsers/compute/describe_images_tests.rb, tests/requests/compute/helper.rb
Calling `Fog::Compute::AWS::Images#all` fails with the error: `Excon::Error::Socket: 25:28: FATAL: Document is empty (Nokogiri::XML::SyntaxError)`. 
This was because the parser was calling `Time.parse` on `nil` creationDate values:
```
when 'creationDate'
@image[name] = Time.parse(value)
```
This commit ensures nil or blank `creationDate` fields are not parsed. It also adds a test for `Fog::Parsers::Compute::AWS::DescribeImages` which wasn't present before.
Fixes https://github.com/fog/fog-aws/issues/273.
=> Fix Fog::Compute::AWS::Images#all

lib/fog/aws/models/storage/file.rb
The file model currently only supports using the default kms key, this adds support for passing a specific key id to use.
=> Allow specifying kms key id to use

CONTRIBUTING.md, LICENSE.md, lib/fog/aws.rb, lib/fog/aws/service_mapper.rb
=> Migrate Service mapper from Fog

lib/fog/aws/requests/compute/copy_snapshot.rb
This PR will allow to use `Encrypted` and `KmsKeyId` parameters while copying snapshots.
In other words will allow to encrypt a copy of an unencrypted snapshot.
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopySnapshot.html
=> Add ability to encrypt a copy of an unencrypted snapshot

lib/fog/aws/parsers/compute/describe_vpcs.rb
handle the case where item ends up being "associated" instead of a staring beginning with true or false
=> Issue #387 Fog::Compute::AWS::Vpcs returns VPCs with nil ids

lib/fog/aws/requests/auto_scaling/detach_instances.rb
React request works as expected. This change only affects mock mode.
=> Fix detaching instances from auto scaling group.

.travis.yml
Since fog-core is pinned in the gemspec, this is only useful information for upcoming upgrades to fog-core.
=> allow Gemfile-edge travis builds to fail

lib/fog/aws/models/compute/vpc.rb, lib/fog/aws/parsers/compute/describe_vpcs.rb, lib/fog/aws/requests/compute/create_vpc.rb, tests/requests/compute/vpc_tests.rb
This PR fixes problems with VPC parser + adds `cidr_block_association_set` attribute to model.
https://github.com/fog/fog-aws/issues/379 was not sufficient – VPC list still contains duplicates with invalid status.
**NB:** `cidr_block_association_set` and `ipv_6_cidr_block_association_set` are array of hashes (currently `ipv_6_cidr_block_association_set` is a Hash)
=> Fix VPC parser

lib/fog/aws/models/compute/subnet.rb, lib/fog/aws/parsers/compute/create_subnet.rb, lib/fog/aws/parsers/compute/describe_subnets.rb, lib/fog/aws/requests/compute/create_subnet.rb, lib/fog/aws/requests/compute/describe_subnets.rb, tests/requests/compute/subnet_tests.rb
* Add new attribute `default_for_az` to `Subnet` model;
* Update parsers to take into account new attribute;
* Fix comments and tests for `map_public_ip_on_launch` attribute.
=> Add `default_for_az` attribute to subnet

.travis.yml, fog-aws.gemspec, gemfiles/Gemfile-ruby-1.8.7, gemfiles/Gemfile-ruby-1.9, lib/fog/aws/requests/kinesis/put_record.rb, lib/fog/aws/requests/kinesis/put_records.rb, lib/fog/aws/requests/storage/put_object.rb, tests/helpers/collection_helper.rb, tests/models/storage/file_tests.rb, tests/models/storage/url_tests.rb, tests/requests/storage/object_tests.rb
Users requiring ruby 1.9 or older should use the main fog gem.
=> Drop Ruby<2.0 support

lib/fog/aws/compute.rb, lib/fog/aws/mock.rb, lib/fog/aws/requests/compute/create_route_table.rb, lib/fog/aws/requests/compute/create_security_group.rb
When you create some resources in VPC-enabled environment (security groups, servers, load balaners etc.) AWS automatically attaches it to the default VPC. I am trying to emulate the same behavior in mocked mode. 
In order to to it I am going to create following resources:
- default vpc;
- internet gateway;
- routes table;
- subnets for each availability zone.
It's not possible to create such resources using requests cause:
1. It doesn't accept some attributes (e.g. `is_default` or `default_for_az`).
2. It creates resources in :pending state.
So I am going to push raw data to `data` collection.
Also I don't think it should be created by default because it may break some existing specs. So I propose to add a new method `Fog::Compute::AWS::Mock#setup_default_vpc!`. All data is stored in the …
=> Add emulation of default VPC to mocked mode.

lib/fog/aws/models/rds/instance_option.rb, lib/fog/aws/parsers/rds/describe_orderable_db_instance_options.rb, lib/fog/aws/requests/rds/describe_orderable_db_instance_options.rb, tests/requests/rds/helper.rb, tests/requests/rds/instance_option_tests.rb
While looking at issue #371 I noticed that the AWS API returns more data than was being exposed by fog, so I updated the model and parser to expose the remaining items and fixed a mismatch on checking for IOPS Support.
=> Update rds instance options model

lib/fog/aws/models/compute/flavors.rb
This adds the [P3 Instance Types](https://aws.amazon.com/ec2/instance-types/).  I'm following the same pattern in [this PR](https://github.com/fog/fog-aws/pull/362).  Let me know if there are any issues.  
cc: @Caged @jdmaturen
=> Adding AWS P3 Tesla GPU instance types

lib/fog/aws/compute.rb
Using exponential backoff alone is not adequate when launching multiple instances simultaneously. Jitter added to compensate for this.
=> Add jitter to exponential backoff

lib/fog/aws/requests/lambda/invoke.rb
`Fog::Json` doesn't exist, so the call to `Fog::Json.encode` failed when providing a `ClientContext` as parameter to `Fog::Lambda#invoke`.
Changing to `Fog::JSON` (all-capitals) resolved this issue.
=> Resolving issue where `Fog::Json` was called instead of `Fog::JSON`.

lib/fog/aws/requests/compute/authorize_security_group_egress.rb, lib/fog/aws/requests/compute/authorize_security_group_ingress.rb, lib/fog/aws/requests/compute/create_network_interface.rb, lib/fog/aws/requests/compute/create_security_group.rb, lib/fog/aws/requests/compute/create_vpc.rb, lib/fog/aws/requests/compute/delete_security_group.rb, lib/fog/aws/requests/compute/describe_network_interface_attribute.rb, lib/fog/aws/requests/compute/describe_security_groups.rb, lib/fog/aws/requests/compute/modify_network_interface_attribute.rb, lib/fog/aws/requests/compute/revoke_security_group_egress.rb, lib/fog/aws/requests/compute/revoke_security_group_ingress.rb, lib/fog/aws/requests/efs/create_mount_target.rb, lib/fog/aws/requests/elb/create_load_balancer.rb, tests/models/efs/mount_target_tests.rb, tests/requests/compute/network_interface_tests.rb, tests/requests/efs/file_system_tests.rb
Match on the correct description.
Fixes #347
=> fix default_security_group detection

lib/fog/aws/models/compute/address.rb, lib/fog/aws/parsers/compute/describe_addresses.rb
Hello guys, just a little PR for adding elastic ip's private_ip_address attributes (model address). (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAddresses.html)
Thanks.
=> Expose elastic ip's private_ip_address

README.md
Unless I've completely missed it, I can't easily find a link to the (excellent) documentation for `fog-aws` — it'd be nice to include it directly in the README.
=> Include link to full documentation

fog-aws.gemspec, lib/fog/aws/models/compute/volume.rb, lib/fog/aws/models/elb/backend_server_descriptions.rb, lib/fog/aws/models/elb/listeners.rb, lib/fog/aws/models/elb/load_balancer.rb, lib/fog/aws/models/elb/load_balancers.rb, lib/fog/aws/requests/elb/create_load_balancer_listeners.rb, tests/models/compute/volume_tests.rb
=> fog-core 2.x, fog-json 1.x

lib/fog/aws/models/compute/volume.rb, tests/models/compute/volume_tests.rb
`s/service/server/` in `Volume#save`.  Fixes attaching after initialization.
Require users to call `Volume#attach(server, device)` to attach a volume after it's created.  `Volume#server=(new_server)` having a side-effect of attaching a volume is confusing.
`Volume#device` set on `Volume#initialize` will be lost when calling `Volume#wait_for` in fog-core ~> 2.0.
BREAKING CHANGE
`Volume#server=` is removed.
=> fix: attach volume on #save, remove #server=

lib/fog/aws/requests/dns/change_resource_record_sets.rb
Sadly these need to be manually updated.
Fortunately it's now simpler as Amazon publish this info.
=> Support new Paris and AP Osaka load balancers in DNS

lib/fog/aws/models/compute/flavors.rb
Hey, just found a little error, c1.xlarge flavors actually have 8 cpus, not 20.
See : https://aws.amazon.com/ec2/previous-generation/
=> Fix c1.xlarge cpu count

lib/fog/aws/compute.rb
To address: https://github.com/fog/fog-aws/issues/448
#1 `retry_if_over_limit` to disable retries fully
#2 `retry_jitter_magnitude` to provide a magnitude to jitter (default same)
#3 replace `splin lock` with `sleep`
=> Parameterized retry

lib/fog/aws/models/compute/flavors.rb
Updated from data available here:
- https://aws.amazon.com/ec2/pricing/on-demand/
- https://aws.amazon.com/ec2/previous-generation/
=> Fix & update aws flavor (provided in GiB) to Megabytes (floor rounded).

lib/fog/aws/models/efs/file_system.rb, lib/fog/aws/requests/efs/create_file_system.rb, tests/requests/efs/helper.rb
These parameters are:
* encrypted
* kms_key_id
Both are optional, but encrypted MUST be true if kms_key_id is specified.
I did not add the additional fields to the tests because the PerformanceMode was not included in the tests, and I  was trying to keep things consistent. But I am happy to update the tests, and I can try to add overriding the PreformanceMode field as well.
=> Add encryption to EFS FileSystem creation

lib/fog/aws/models/compute/servers.rb
Retry is necessary because AWS is eventually consistent. Not doing so
occassionally results in instance tags not being applied.  The specific
error is:
The instance ID 'i-0e800893aa8d116a1' does not exist (Fog::Compute::AWS::NotFound)
Refer to AWS docs regarding eventual consistency's
InvalidInstanceID.NotFound error
=> Retry if  instance not found when adding EC2 tags

lib/fog/aws/auto_scaling.rb, lib/fog/aws/models/auto_scaling/group.rb, lib/fog/aws/requests/auto_scaling/set_instance_protection.rb, tests/requests/auto_scaling/auto_scaling_tests.rb
This PR adds support for SetInstanceProtection endpoint.
https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-termination.html#instance-protection
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_SetInstanceProtection.html
=> SetInstanceProtection endpoint for auto scaling groups support

lib/fog/aws/models/rds/server.rb, lib/fog/aws/parsers/rds/db_parser.rb
This pull request adds the missing `enable_iam_database_authentication` attribute to the `RDS::Server` model and maps it to the `EnableIAMDatabaseAuthentication` parameter on the [AWS RDS API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html).
Thanks for reviewing! 😄
=> Add missing attribute to RDS server

lib/fog/aws/compute.rb
As suggested here: https://github.com/fog/fog-aws/pull/451
```
options.has_key?(:retry_request_limit_exceeded) ? options[:retry_request_limit_exceeded] : true
```
becomes:
```
options.fetch(:retry_request_limit_exceeded, true)
```
=> Simplify constructor

lib/fog/aws/storage.rb
Adds generic support for CN regions in storage provider since AWS seem to be spinning up new ones.
=> Storage region support for cn-northwest-1

lib/fog/aws/models/compute/flavors.rb
It's not a 0 bit instance. It's a 32bit instance.
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Fix t1.micro bits

lib/fog/aws/storage.rb
As per https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html
Fixes #462
=> Escape / in presigned URLs

lib/fog/aws.rb, lib/fog/aws/dns.rb, lib/fog/aws/models/dns/record.rb, lib/fog/aws/models/dns/records.rb, lib/fog/aws/models/dns/zone.rb, lib/fog/aws/models/dns/zones.rb, lib/fog/aws/parsers/dns/change_resource_record_sets.rb, lib/fog/aws/parsers/dns/create_hosted_zone.rb, lib/fog/aws/parsers/dns/delete_hosted_zone.rb, lib/fog/aws/parsers/dns/get_change.rb, lib/fog/aws/parsers/dns/get_hosted_zone.rb, lib/fog/aws/parsers/dns/health_check.rb, lib/fog/aws/parsers/dns/list_health_checks.rb, lib/fog/aws/parsers/dns/list_hosted_zones.rb, lib/fog/aws/parsers/dns/list_resource_record_sets.rb, lib/fog/aws/requests/dns/change_resource_record_sets.rb, lib/fog/aws/requests/dns/create_health_check.rb, lib/fog/aws/requests/dns/create_hosted_zone.rb, lib/fog/aws/requests/dns/delete_health_check.rb, lib/fog/aws/requests/dns/delete_hosted_zone.rb, lib/fog/aws/requests/dns/get_change.rb, lib/fog/aws/requests/dns/get_health_check.rb, lib/fog/aws/requests/dns/get_hosted_zone.rb, lib/fog/aws/requests/dns/list_health_checks.rb, lib/fog/aws/requests/dns/list_hosted_zones.rb, lib/fog/aws/requests/dns/list_resource_record_sets.rb, lib/fog/aws/service_mapper.rb, tests/requests/dns/change_resource_record_sets_tests.rb
Fixes fog-core deprecation warning
```
[fog][DEPRECATION] Unable to load Fog::AWS::DNS
[fog][DEPRECATION] The format Fog::DNS::AWS is deprecated
```
Part of #466
=> Rename DNS::AWS to AWS::DNS

lib/fog/aws/models/compute/flavors.rb
Hi,
I've added missing generation 5 compute instance flavors: T3, M5d, C5d, R5, R5d.
=> Add missing generation 5 compute instance flavors

lib/fog/aws/models/compute/flavors.rb
AWS added new EC2 instance types with AMD CPUs.
https://aws.amazon.com/blogs/aws/new-lower-cost-amd-powered-ec2-instances/
=> Add AMD CPU instance types

lib/fog/aws/parsers/compute/describe_security_groups.rb, lib/fog/aws/requests/compute/describe_security_groups.rb
Hello,
In this PR I did:
- Added filters MaxResults and NextToken to describe_security_groups.
- Updated the describe security group parser to add nextToken in the result load.
Thanks in advance for your time
=> Add MaxResults filter to describe security groups

lib/fog/aws/models/rds/cluster.rb, lib/fog/aws/models/rds/server.rb
1. A non-functional commit, just a comment. I'm not sure the commit from December adding in the check for 'active' in the ready? method of RDS::Cluster is going to work, specifically for Aurora clusters. Please see my comment.
2. Updated the check for the "aurora" engine value in RDS::Server to check if the value starts with "aurora" instead of equaling "aurora." Early versions of Aurora did use just "aurora" for the engine. But that changed when Aurora started supporting more than just MySQL.
=> Fix for Aurora Server Provisioning.

lib/fog/aws/requests/dynamodb/update_item.rb
1. The `AttributeUpdates` option is deprecated and should no longer be passed in by default, unless the deprecated behavior is requested.
2. Updated the documentation to reflect the current [AWS DynamoDB update_item](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/dynamo-example-update-table-item.html) documentation.
=> Correct DynamoDB update_item method

lib/fog/aws/requests/storage/get_bucket_location.rb, lib/fog/aws/requests/storage/get_service.rb
This PR fixes some methods to make them work with acceleration enabled #505
+ get_bucket_location uses host instead of path_style
+ get_service explicitly uses s3.amazonaws.com as per docs https://docs.aws.amazon.com/AmazonS3/latest/API/RESTServiceGET.html
=> Fix some requests when S3 acceleration is enabled

lib/fog/aws/storage.rb
In cases where you have CNAME pointing to the S3 bucket, implicitly combining the bucket name and overriden host prevents signed url generation with CNAME pointing to the bucket.  
This change fixes the issue. Potential gotcha is now you cannot override the hostname for region, but it should allow you to specify the exact hostname (along with bucket name) if needed.
=> Avoid using bucket_name.host if host is overriden.

lib/fog/aws/elb.rb, lib/fog/aws/parsers/elb/describe_load_balancers.rb
Hello,
In this PR I added the possibility to choose the ELB service version and added some attributes on the describe_load_balancer parser corresponding to the newest version.
This changes was implemented to add the compatibility with "ELBv2" which is on the ELB api version ` 2015-12-01`.
- The documentation related to this version is here: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/Welcome.html
- You can also find the corresponding new LoadBalancer attributes here: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancer.html 
Thanks in advance for your time.
=> Enhance/handle ELBv2 api version

lib/fog/aws/glacier.rb, tests/requests/glacier/tree_hash_tests.rb
As discussed in #520 the previous Fog::AWS::Glacier::TreeHash::add_part works only in very specific and undocumented circumstances which are luckily exactly the ones actually happening when using the gem.
However, it's not that hard to make it work truly generally, replacing the list of digests by stack with one digest for every power of two and additional digest object with unfinished last chunk.
As additional bonus, it will reduce the amount of memory consumed when processing large files, although I doubt it will be relevant unless it will go into petabytes.
=> Add support for generating tree hash tests by adding unaligned parts.

lib/fog/aws/requests/lambda/invoke.rb
According to [documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html) we should use `X-Amz-Invocation-Type` instead of `X-Amz-Client-Type`.
=> Fixed issue with InvocationType header for AWS Lambda

lib/fog/aws.rb
As mentioned in #527 I simply added `ap-east-1` to the list of regions in `Fog::AWS.regions`. I also did some smoke tests with out AWS accounts for some EC2 and S3 API calls which just seem to work fine.
Please note, that `ap-east-1` (Hong Kong) is not enabled by default for every AWS account and you might need to enable it before you can use this regions (just in case someone wants to check this).
fixes #527
=> Add ap-east-1 (Hong Kong) to Fog::AWS.regions

lib/fog/aws/parsers/compute/create_subnet.rb, lib/fog/aws/parsers/compute/describe_subnets.rb
Hello,
Subnet's parsing was broken due to ipv6CidrBlockAssociationSet which include an `item` element and which was not taking in account, then the `item` element was taking in account for the subnet object instead of for the ipv6CidrBlockAssociationSet block.
Exemple:
*before*
```
{
"subnetSet"=>
[{
"tagSet"=>{},
"subnetId"=>"subnet-xxxxxxxx",
"state"=>"associated",
"vpcId"=>"vpc-xxxxxxxx",
"cidrBlock"=>"172.31.1.0/16"
},
{   
"tagSet"=>{"Name"=>"MyName"},
"availableIpAddressCount"=>"X",
"availabilityZone"=>"eu-west-1a",
"defaultForAz"=>true,
"mapPublicIpOnLaunch"=>true
}],
"requestId"=>"3173af67-7ba1-4193-ae67-9b00e1ca35f7"
```
*after*
```
{
"subnetSet"=>
[{
"tagSet"=>{"Name"=>"MyName"},
"subnetId"=>"subnet-xxxxxxxx",
"state"=>"available",
"vpcId"=>"vpc-xxxxxxxx", …
```
=> Fix subnet's parsings

lib/fog/aws/models/compute/vpc.rb, lib/fog/aws/requests/compute/create_vpc.rb, tests/requests/compute/vpc_tests.rb
**Bug:** 
When you try to create a VPC with tenancy set to dedicated like this:
`ec2.vpcs.create(cidr_block: request.cidr, tenancy: 'dedicated')`
the tenancy is set to "default" when the creation request is done.
**RC:**
VPC#save was not passing to create_vpc request the InstanceTenancy option.
**Fix:**
- Changed #save method to pass InstanceTenancy argument.
- Corrected mock response and added a test case.
=> Fix VPC tenancy on creation

lib/fog/aws/models/storage/directory.rb
Hello,
A quick PR to remove `location`attribute from directory model, which is not usefull as:
- It's not an attributes from directories listing (https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html) (Fog use the API endpoint `GET service` but I didn't find it in the documentation and it have the same result than this one)
- It is implemented by a method which do the correct call to get it: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/directory.rb#L57-L64
Futhermore without this fix the behavior on pry is weird; The listing is long and the rendering is weird (event if the Fog object correctly respond to each attributes/methods):
*before*
```
[#<Fog::AWS::Storage::Directory:0x2ad1edfdc4f8>]
```
*after*
```
[
<Fog::AWS::Storage::Directory …
```
=> Remove useless attribute location from directory model

lib/fog/aws/parsers/elbv2/describe_load_balancers.rb, tests/parsers/elbv2/describe_load_balancers_tests.rb, tests/requests/elbv2/helper.rb
Hello,
In this PR I fix a little mistake of https://github.com/fog/fog-aws/pull/534;
The `availability_zone` attributes inside the parser was not correctly reset, then when an other `availability_zone` than the first one had an attribute `LoadBalancerAddresses` we had an error due to trying to adding an object inside a `nil` attributes of the `availability_zone` hash.
@geemus Sorry for this mistake !
=> Fix load balancers parser to handle more than one availability zone with addresses

LICENSE.md, README.md, bin/console, bin/setup
I added S3 examples to the README. I'm not sure if it's **the** best place to be but for now it's very concise and short so I think it's good. Let me know if you agree or if I should move it somewhere else, maybe a wiki.
I also added `bin/setup` and `bin/console` files to the gem. These files are generated automatically if you create a gem using Bundler, they help with the development setup and also makes it easier to experiment with gem. I also upgraded the README with these file instructions.
=> Improve documentation and development setup

lib/fog/aws/requests/sts/assume_role_with_web_identity.rb
Fixes `Fog::AWS::STS::ValidationError (1 validation error detected: Value null at 'webIdentityToken' failed to satisfy constraint: Member must not be null)`
=> Adds missing param WebIdentityToken for the request to the AWS api

lib/fog/aws.rb
Added the following to `lib/fog/aws.rb`
**me-south-1** - Middle East (Bahrain)
**us-gov-east-1** - AWS GovCloud (US) East
**NOTES**
1. **me-south-1** is not enabled by default for every AWS account and you might need to enable it before you can use this region
2. **us-gov-east-1** is part of AWS GovCloud (US)
=> Adding two missing regions to Fog::AWS.regions

fog-aws.gemspec
The scripts in `bin` appear intended for development, and have very generic names. They should not be installed as executables when installing the gem. Instead, change such executables to come from `exe`, which is more common.
=> Don’t install development scripts

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
AWS has introduced [Instance Metadata Service Version 2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#instance-metadata-v2-how-it-works) which improves security by moving to a session-oriented model that requires first retrieving a token via a `PUT` request that must be supplied with each `GET` request.
Currently, the gem throws an error if your EC2 instance is configured to only allow IMDSv2-based requests, which is recommended for maximum security.
IMDSv2 is supported by the metadata API without any configuration by the end-user, so switching the `CredentialFetcher` to use it improves security, fixes this error condition and should not have any negative effects for existing users.
=> Add support for IMDSv2 in CredentialFetcher

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
Fixes #560 
To address edge cases where the IMDSv2 API does not work for users, I have added support for the `CredentialFetcher` to fall-back to not using IMDSv2 tokens when the API call to retrieve the token fails 3 times, or when the option `:disable_imds_v2` is set to true. This is similar to the approach employed by [`aws-sdk-core`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/instance_profile_credentials.rb).
=> Gracefully handle failure of IMDSv2 and allow fallback to IMDSv1

lib/fog/aws/models/compute/flavors.rb
Fixes #563 
Removes duplicate R5 type instances
Fixes naming of u-6tb1.metal
Removes ambiguity in naming of T and M types
=> Fix naming of various AWS compute flavors

lib/fog/aws/models/compute/vpc.rb
`is_default?` requires attribute `IsDefault` to be defined. This is different to using `Kernel#require`
=> Fix VPC model is_default requires

Gemfile, lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
The action mentioned on the PR title can be found here: [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html#API_AssumeRoleWithWebIdentity_Examples)
The `nokogiri` gem was added to parse the XML response from the host.
=> Add AssumeRoleWithWebIdentity to fetch_credentials

lib/fog/aws/models/storage/file.rb, lib/fog/aws/parsers/storage/upload_part_copy_object.rb, lib/fog/aws/requests/storage/upload_part_copy.rb, lib/fog/aws/storage.rb, tests/requests/storage/multipart_copy_tests.rb
This enables copying of files larger than 5 GB.
Closes https://github.com/fog/fog-aws/issues/577
=> Add support for multipart Fog::AWS::Storage::File#copy

README.md, lib/fog/aws/models/storage/file.rb, tests/requests/storage/multipart_copy_tests.rb
This improves transfer performance significantly. For a 6 GB transfer, instead of taking several minutes to copy, it now appears to take 36 seconds on a local EC2 instance.
=> Add multi-threaded support for File#copy

lib/fog/aws/requests/storage/shared_mock_methods.rb, tests/requests/storage/object_tests.rb
When passing a file object that has reached end-of-file to the `put_object` mock, an empty string is saved to the uploaded file body property. This is because subsequent `read` calls will return an empty string as there is no more to read. Sometimes code does some operations such as reading and validating a file before uploading to S3. The real service seems to be fine with the file being at EOF and still uploads the data, however I noticed the mocks are not
Rewinds the pointer of the file object if the file is at EOF
=> Rewind pointer if file is eof on put_object mock

lib/fog/aws/models/storage/file.rb
If an error occurred in a multipart copy, the following error would
show:
```
undefined local variable or method `error' for #<Fog::AWS::Storage::File:0x00007f98212f9d68>
Did you mean?  errors
```
=> Fix NameError in multipart copy

lib/fog/aws/models/storage/file.rb, lib/fog/aws/requests/storage/upload_part_copy.rb, tests/requests/storage/multipart_copy_tests.rb
Previously attempting to use S3 server side encryption headers
(e.g. `x-amz-server-side-encryption`) would fail when attempting to use
`File#copy` because the method would pass these headers to the `UploadPartCopy`
(https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html)
API call. However, this would fail with an error:
```
<Code>InvalidArgument</Code>
<Message>x-amz-server-side-encryption header is not supported for this operation.</Message>
<ArgumentName>x-amz-server-side-encryption</ArgumentName>
<ArgumentValue>AES256</ArgumentValue>
```
This header can and should be used in the `CompleteMultipartUpload`
call. To support this, we filter out unknown headers in the
`UploadPartCopy`.
=> Filter unknown UploadPartCopy paramaters

.travis.yml, tests/helpers/succeeds_helper.rb
I am afraid there are some issues on Ruby 3.0, so this might not work right away. Also, not sure about the PPC64
=> Enable test on Ruby 3.0

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
When using IAM roles for Service Accounts (IRSA), annotated pods get a number of
environment variables:
1. `AWS_WEB_IDENTITY_TOKEN_FILE`
2. `AWS_ROLE_ARN`
3. `AWS_DEFAULT_REGION`
4. `AWS_REGION`
`AWS_ROLE_SESSION_NAME` is not usually included. The AWS SDK falls back
to using `default_name` as the default session name if
`AWS_ROLE_SESSION_NAME` is not provided. From
https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-role_session_name.html:
> If you don't provide this value, a session name is generated
> automatically if the profile assumes a role.
=> Generate a default session name if one is not provided

lib/fog/aws/models/storage/files.rb, tests/models/storage/files_tests.rb
Some S3 providers (e.g. Ceph) appear to send responses with lowercase
HTTP headers (e.g. content-length vs. Content-Length). This appears to
confuse fog-aws.
The attributes were not being loaded because the aliases did not contain
the lowercased version, and the attributes themselves use underscores
rather than dashes.
To fix this issue, we normalize the headers by fetching the value via
excon's case-insensitive lookup, storing the canonical key, and then
deleting other matches.
=> Fix handling of lowercased HTTP headers

lib/fog/aws/storage.rb, tests/models/storage/directory_tests.rb, tests/requests/storage/bucket_tests.rb
When a bucket url like `bucket.s3.amazonaws.com` with bucket name `bucket`is present in params passed into equest_params method, it should not duplicate the subdomain.
**current behavior**: bucket.bucket.s3.amazonaws.com
**expected behavior**: bucket.s3.amazonaws.com
Fixes: https://github.com/fog/fog-aws/issues/594
=> Fixes domain name duplication in url

lib/fog/aws/requests/storage/get_object.rb
adapt storage#get_object with a block given.  
ruby 3 raises an error when instantiating a proc without a block
@see https://blog.saeloun.com/2019/09/02/ruby-2-7-proc-without-block-warning.html
=> fix storage for ruby 3.0

lib/fog/aws/compute.rb, lib/fog/aws/models/compute/security_group.rb, lib/fog/aws/parsers/compute/describe_security_groups.rb, lib/fog/aws/requests/compute/authorize_security_group_ingress.rb, lib/fog/aws/requests/compute/describe_security_groups.rb, tests/requests/compute/security_group_tests.rb
This change adds adding IPv6 security group rules.
The current security groups tests are pending, so I didn't add any new tests.
This fork does allow me to authorize and revoke IPv6 rules for ingress.
I could not test the egress implementation, as I'm currently not using it.
=> Add IPv6 support for Ingress Security Groups

fog-aws.gemspec
This will add following IAM related JSON files back into the gem file:
* lib/fog/aws/iam/default_policies.json
* lib/fog/aws/iam/default_policy_versions.json
These files appear to have been accidentally dropped as of v3.10.0.
---
I found this when running a test suite for an internal project, on a call to `Fog::AWS::IAM.get_server_certificate`, where it reported that `lib/fog/aws/iam/default_policies.rb` was missing.
Since, this is a problem with the contents of the gem, I do not think that there is a test to update.  I have also not opened a separate issue for this bug, because I think that this PR fixes the problem. But if you want a separate issue for tracking I am happy to open one.
=> Add json files to the gem file

fog-aws.gemspec
This gem contains test files totaling 1.4MB, which can be excluded from the package since they should not be needed at runtime.
```
$ du -sh *
80K	CHANGELOG.md
4.0K	CONTRIBUTING.md
8.0K	CONTRIBUTORS.md
4.0K	LICENSE.md
4.0K	README.md
4.0K	fog-aws.gemspec
6.1M	lib
1.4M	tests
```
According to https://github.com/rubygems/guides/issues/90, `spec.test_files` is no longer in use.
=> Exclude test files from gem

fog-aws.gemspec, lib/fog/aws/requests/compute/create_network_interface.rb, lib/fog/aws/requests/compute/create_subnet.rb
The ipaddr module is part of Ruby itself and can be used to check for range inclusion.
I don't have the capacity to test this properly and it doesn't appear to be covered by tests. Please review carefully.
=> Drop ipaddress dependency in favor of built in ipaddr

.github/workflows/ruby.yml, .github/workflows/stale.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
> Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
https://www.legitsecurity.com/blog/github-privilege-escalation-vulnerability
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

lib/fog/aws/requests/rds/add_tags_to_resource.rb, lib/fog/aws/requests/rds/list_tags_for_resource.rb, lib/fog/aws/requests/rds/remove_tags_from_resource.rb
Fixed RDS tags issue for AWS GovCloud Account regions.
=> RDD tags issue in AWS GovCloud Account regions.

CHANGELOG.md
It seems that `RDD` is a typo of `RDS`.
=> Fix a typo in CHANGELOG

lib/fog/aws/models/compute/flavors.rb
Hi all I recently added a few ARM64 instances at EY and I thought I'd do a PR against the main repo for the types missing.
You can check the instance information at the usual spot - https://aws.amazon.com/ec2/instance-types/
=> add x2gd and t4g instance flavours

lib/fog/aws/requests/storage/sync_clock.rb
Perform an unauthenticated GET request to the root S3 URL to prevent 403 errors if the user doesn't have ListBuckets permissions
=> change sync_clock to plain GET

lib/fog/aws/parsers/iam/get_group_policy.rb, lib/fog/aws/parsers/iam/get_role_policy.rb, lib/fog/aws/parsers/iam/get_user_policy.rb, lib/fog/aws/parsers/iam/policy_version.rb
Resolves https://github.com/fog/fog-aws/issues/653
Replace with URI.decode_www_form_component which has been available since Ruby 1.9
I'm not sure if there's any tests to add / update.
Based on https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/lint/uri_escape_unescape.rb, we have three options:
1. CGI.escape
2. URI.encode_www_form
3. URI.encode_www_form_component
2 is complicated because it returns an Array instead of a String. 3 seems a better fit than 1. Also:
```
irb(main):001:0> string = '?a=%09%0D'
=> "?a=%09%0D"
irb(main):002:0> URI.decode_www_form_component(string) == URI.decode(string)
(irb):2: warning: URI.unescape is obsolete
=> true
irb(main):004:0> require 'cgi'
=> true
irb(main):005:0> CGI.escape(string)
=> "%3Fa%3D%2509%250D"
irb(main):006:0> CGI.escape(string) …
```
=> Replace URI.decode as obsolete, and removed in Ruby 3.0

lib/fog/aws.rb
Add new AWS region "ap-southeast-3" - Asia Pacific (Jakarta)
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
=> Add new AWS region "ap-southeast-3" - Asia Pacific (Jakarta)

lib/fog/aws/models/storage/file.rb, lib/fog/aws/storage.rb
On a FIPS system, calling `OpenSSL::Digest::MD5` fails.  The Go AWS SDK has an option of disabling `Content-Md5` in these cases (https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config.WithS3DisableContentMD5Validation). This commit adds a `disable_md5_content_validation` flag to emulate this behavior for multipart uploads. In this mode, `Content-Md5` is omitted in multipart chunks. fog-aws already sends along the `x-amz-content-sha256` header.
=> Support disabling of Content-MD5 for FIPS

lib/fog/aws/models/storage/file.rb
Previously fog-aws would attempt to generate all the SSE-C headers even if encryption were not active. However, on a FIPS system, MD5 is not available. This commit modifies the UploadPart API request to compute the SSE-C headers only when they are needed.
=> Only compute SSE-C headers when needed in multipart upload

lib/fog/aws/requests/storage/get_service.rb
=> s3: remove hardcoded host

lib/fog/aws/requests/storage/sync_clock.rb
We use S3 Transfer Acceleration which was added in https://github.com/fog/fog-aws/pull/505.
In 3.15.0 it [was broken](https://github.com/fog/fog-aws/pull/651):
```
vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:170:in `connect': no address for s3-accelerate.amazonaws.com (Resolv::ResolvError) (Excon::Error::Socket)
from vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/ssl_socket.rb:193:in `connect'
from vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:51:in `initialize'
from vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/ssl_socket.rb:10:in `initialize'
from vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/connection.rb:474:in `new'
from vendor/bundle/ruby/3.1.0/gems/excon-0.99.0/lib/excon/connection.rb:474:in `socket'
from …
```
=> Fix S3 Transfer Acceleration

lib/fog/aws.rb
Add missing AWS region: me-central-1 (Middle East (UAE))
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
=> gopalcoupa:add-me-central-1

lib/fog/aws/requests/storage/sync_clock.rb
Correct the sync_clock_url method so that it is possible to connect to a port other than the default one.
Use case where it needs to be a different port than the default one, is using localstack s3 in a development environment.
=> Change method sync_clock_url to use localstack set a different port

.github/workflows/ruby.yml
This PR just adds Ruby 3.2 to the test matrix.
=> CI against Ruby 3.2

lib/fog/aws/auto_scaling.rb, lib/fog/aws/beanstalk.rb, lib/fog/aws/cdn.rb, lib/fog/aws/cloud_formation.rb, lib/fog/aws/cloud_watch.rb, lib/fog/aws/compute.rb, lib/fog/aws/data_pipeline.rb, lib/fog/aws/dns.rb, lib/fog/aws/dynamodb.rb, lib/fog/aws/ecs.rb, lib/fog/aws/elasticache.rb, lib/fog/aws/elb.rb, lib/fog/aws/elbv2.rb, lib/fog/aws/emr.rb, lib/fog/aws/glacier.rb, lib/fog/aws/iam.rb, lib/fog/aws/kinesis.rb, lib/fog/aws/kms.rb, lib/fog/aws/lambda.rb, lib/fog/aws/rds.rb, lib/fog/aws/redshift.rb, lib/fog/aws/ses.rb, lib/fog/aws/simpledb.rb, lib/fog/aws/sns.rb, lib/fog/aws/sqs.rb, lib/fog/aws/storage.rb, lib/fog/aws/support.rb, tests/credentials_tests.rb
This is a solution for https://github.com/fog/fog-aws/issues/683
I try to fix three points in this PR.
1. Fix `[fog][WARNING] Unrecognized arguments: sts_endpoint` warring
- this is the main topic since #683
2. Add another related parameter such as a `region`
- In coding, I found the `Unrecognized arguments:` warning is not only `sts_endpoint`. So I try to fix other parameters' warnings.
3. Add tests that prevent those warnings from automatically
- Currently, we need to manually cross-check how to correct parameters that are set on each AWS Service class when the corresponding AWS new services or add extra parameters to CredentialFetcher.
- So I try to do that operation in the test.
=> Prevent `Unrecognized arguments: sts_endpoint` warning

lib/fog/aws/storage.rb
Resolves #690
Excon's default configuration retries HTTP 4xx class errors, which we generally can't expect to be resolved by retry. Combined with relatively recent retry config added in https://github.com/fog/fog-aws/issues/674 we were seeing S3 calls to non-existent objects take multiple seconds when made via fog-aws.
See the issue for detailed explanation of the underlying cause.
Though this resolves the problem, I question whether it's the right approach:
- it's odd that the default retry behaviour (and connection options) for `Fog::AWS::Storage` are different to all the other services covered by fog-aws.
- ~~we create something of a foot gun, because someone who chooses to just configure eg `retry_limit` (or any other arbitrary connection option) will inadvertently set `retry_errors` …
=> Fog::AWS::Storage don't retry client errors

lib/fog/aws.rb
Add ca-west-1 region to region list in aws.rb
This is an attempt to fix the missing region (based on comments in #701 ), my live testing suggests it works, but I am inexperienced with ruby programming.
fixes #701
=> Add ca-west-1 region

lib/fog/aws/signaturev4.rb
To prepare for ruby 3.4.0 and making strings frozen by default, I've stumbled upon this string mutation.
Let me know if you need anything ( I didn't add tests since I assume tests exist for this feature )
=> Fix frozen string literal issue for ruby 3.4.0

fog-aws.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/fog-aws which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
=> Provide a 'Changelog' link on rubygems.org/gems/fog-aws

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
As https://docs.aws.amazon.com/sdkref/latest/guide/feature-region.html#feature-region-sdk-compat describes, the AWS CLI v2 uses AWS_REGION before AWS_DEFAULT_VERSION.
=> Prefer AWS_REGION over AWS_DEFAULT_REGION in credential fetching

lib/fog/aws/requests/storage/put_bucket.rb, tests/requests/storage/bucket_tests.rb
Previously if `Fog.mock!` were used with some other region and the bucket already existed, a warning message, `Your region <region> does not match the default region 'us-east-1'`.
We were seeing a lot of these warnings in our test suite. As far as I can tell, there's no reason why some other region can't be used, so drop this.
=> Drop warning if region is not us-east-1 in mock

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
I'd like to use EKS Pod Identity with fog-aws, so added support for it.
This will resolve #718.
Could anyone please review my code?
=> Added support for EKS Pod Identity.

lib/fog/aws/credential_fetcher.rb, tests/credentials_tests.rb
As described in https://docs.aws.amazon.com/sdkref/latest/guide/ss-endpoints-table.html, the STS endpoint can be configured with the AWS_ENDPOINT_URL_STS environment variable. This might be necessary for users of Amazon Secret Cloud (https://aws.amazon.com/federal/secret-cloud/), for example.
=> Support AWS_ENDPOINT_URL_STS environment variable

lib/fog/aws/ses.rb
Resolves #726 
Have tested it works.
=> Update SES to use AWS SigV4

lib/fog/aws/storage.rb
The Fog::AWS::Utils region_to_host method returns the standard S3 endpoints even when ENV['AWS_USE_FIPS_ENDPOINT']=='true'.  When FIPS is called for, and we are in a region where FIPS endpoints are available,  this method should return the FIPS endpoint.
Furthermore, when S3 Transfer Acceleration (S3TA) is requested by configuration, the above endpoint gets overridden to select the S3TA endpoint.  However, S3TA is not avaialble in GovCloud, and has no FIPS endpoint equivalents.  In this instance, if the region is a GovCloud region, or if FIPS mode is called for, do _not_ override the endpoint to use S3TA.
=> Support FIPS endpoints, disable S3 Transfer Acceleration in GovCloud

lib/fog/aws/kms.rb, lib/fog/aws/parsers/kms/describe_key.rb, lib/fog/aws/parsers/kms/get_public_key.rb, lib/fog/aws/parsers/kms/schedule_key_deletion.rb, lib/fog/aws/parsers/kms/sign.rb, lib/fog/aws/requests/kms/create_key.rb, lib/fog/aws/requests/kms/get_public_key.rb, lib/fog/aws/requests/kms/list_keys.rb, lib/fog/aws/requests/kms/schedule_key_deletion.rb, lib/fog/aws/requests/kms/sign.rb, tests/requests/kms/helper.rb, tests/requests/kms/key_tests.rb
- **add kms test lint fixes**
- **remove unused default key policy constant from KMS create key request**
- **minor cleanup and add first pass at schedule_key_deletion method and mock**
=> kms additions

lib/fog/aws/parsers/compute/describe_instance_status.rb
Resolves https://github.com/fog/fog-aws/issues/734
```
source 'https://rubygems.org'
gem 'fog-aws', git: 'https://github.com/fog/fog-aws.git'
```
```
require 'fog/aws'
INSTANCE_ID = 'i-*****' # provide instance ID
compute = Fog::AWS::Compute.new(
aws_access_key_id:     '***', # provide access key ID
aws_secret_access_key: '***', # provide secret
region:                'us-east-1' # Change region if needed
)
begin
response = compute.describe_instance_status('InstanceId' => [INSTANCE_ID])
statuses = response.body['instanceStatusSet']
if statuses.empty?
puts "No status found for instance #{INSTANCE_ID}"
else
status = statuses.first
puts "Instance #{INSTANCE_ID} status:"
puts "  Instance State: #{status['instanceState']['name']}"
puts "  System Status:  #{status['systemStatus']['status']}" …
```
=> Fix Compute.describe_instance_status parser

lib/fog/aws/parsers/storage/list_objects_v2.rb, lib/fog/aws/requests/storage/list_objects_v2.rb, lib/fog/aws/storage.rb, tests/models/storage/files_v2_tests.rb, tests/requests/storage/list_objects_v2_tests.rb
Fix #741
AWS S3 ListObjectsV2 is the recommended API for listing objects in S3 buckets. It provides better performance and more efficient pagination compared to the original ListObjects API.
Added support for v2 API without integration with list related functionalities, that will be added in the next PR.
```ruby
storage = Fog::Storage.new(provider: 'AWS', region: 'us-east-1')
response = storage.list_objects_v2("my-bucket")
objects = response.body['Contents']
key_count = response.body['KeyCount']
```
```ruby
response = storage.list_objects_v2("my-bucket", 'prefix' => 'photos/')
response = storage.list_objects_v2("my-bucket", 'max-keys' => 1000)
response = storage.list_objects_v2("my-bucket", 'start-after' => 'photos/2023/')
response = storage.list_objects_v2("my-bucket", 'delimiter' => …
```
=> Fix #741 Added list objects v2 api support

lib/fog/aws/models/storage/file.rb
=> storage headers should be rejected in a case-insensitive way
