fog/fog-aws

lib/fog/aws/signaturev4.rb
tests/signaturev4_tests.rb

This fixes issues such as #3381

[AWS|Core] Fix signature v4 non canonicalising header case properly

---

lib/fog/aws/storage.rb

I think this may fix https://github.com/fog/fog/issues/3275
See also: http://stackoverflow.com/questions/27091816/retrieve-buckets-objects-without-knowing-buckets-region-with-aws-s3-rest-api

another attempt at s3 region redirecting

---

lib/fog/aws/rds.rb
lib/fog/aws/requests/sns/create_topic.rb
lib/fog/aws/requests/sns/subscribe.rb
lib/fog/aws/sns.rb

* make mock account_id look more real
* expose region on Mock (already on Real)

simulate sns confirmation message

---

Gemfile
lib/fog/aws/storage.rb
tests/models/storage/url_tests.rb

[AWS|Storage] signed_url should use v2 signature when aws_signature_version is 2

---

tests/models/elasticache/cluster_tests.rb
tests/models/elb/model_tests.rb
tests/models/rds/tagging_tests.rb
tests/requests/elasticache/cache_cluster_tests.rb
tests/requests/rds/tagging_tests.rb

Use Fog::Formatador

---

lib/fog/aws/requests/iam/delete_group_policy.rb
lib/fog/aws/requests/storage/delete_bucket_policy.rb
lib/fog/aws/requests/storage/put_bucket_policy.rb

* mock for delete_group_policy request
* mock for delete_bucket_policy request
* mock for put_bucket_policy request

add missing mocks

---

lib/fog/aws/parsers/compute/describe_images.rb

- volumeType: standard, gp2 or io1
- encrypted: true or false

add 'volumeType' and 'encrypted' to blockDeviceMapping parser

---

lib/fog/aws/models/cloud_watch/alarm.rb
lib/fog/aws/requests/cloud_watch/describe_alarms.rb

* deleted initialization method on cloud watch alarm
* filter alarms by alarm name in describe_alarms request

default namespace and evaluation period on alarm

---

lib/fog/aws/models/storage/files.rb
lib/fog/aws/requests/storage/head_object_url.rb
lib/fog/aws/storage.rb
tests/requests/storage/object_tests.rb

Very similar to get_url. https://github.com/fog/fog-aws/issues/47

Making it easier to get pre-signed head requests

---

lib/fog/aws/requests/compute/authorize_security_group_ingress.rb
tests/models/compute/security_group_tests.rb

* and refactor the authorize_security_group_ingress method a bit

don't allow sg authorization is unknown sgs

---

lib/fog/aws/models/storage/file.rb
tests/models/storage/file_tests.rb

S3 server-side encryption with customer provided encryption doesn't work for multipart uploads since each request must contain encryption key header. This PR includes a configuration option for customer encryption key and includes necessary headers for all multipart requests.
I didn't quite get the test setup running, but manually uploading encrypted files and decrypting them seems to work. Hopefully my attempt to write tests work.

Support customer encryption headers in multipart uploads

---

lib/fog/aws/rds.rb
lib/fog/aws/requests/compute/delete_security_group.rb
tests/requests/compute/security_group_tests.rb

* get a `InUse` error when doing so for realsies

raise when destroying an ec2 firewall authorized to an rds firewall

---

lib/fog/aws/models/compute/flavors.rb

same as https://github.com/fog/fog/pull/3443

[aws|compute] adding support for c4 instance class

---

lib/fog/aws/models/compute/flavors.rb

forgot this flavor in previous PR

[aws|compute] support c4.8xlarge flavor

---

lib/fog/aws/mock.rb
lib/fog/aws/requests/compute/describe_spot_price_history.rb
tests/requests/compute/spot_price_history_tests.rb

Hi folks,
I needed to mock some calls to EC2 describe_spot_price_history API request, so I added a mock class for this kind of request.
I hope you find it useful.
Cheers,

Add mock for EC2 describe_spot_price_history API request

---

lib/fog/aws/mock.rb
lib/fog/aws/requests/compute/request_spot_instances.rb
tests/requests/compute/spot_instance_tests.rb

Hi folks, it's me again.
This time I'm sending another mock but for request_spot_instance EC2 api request.
I hope you find it useful.
Thanks,

Add mock for EC2 request_spot_instances API request

---

lib/fog/aws/models/elasticache/cluster.rb
lib/fog/aws/parsers/elasticache/cache_cluster_parser.rb

retrieves the configuration endpoint from the response (as used by the auto discovery feature for memcached elasticache clusters)

Parse elasticache configuration endpoint from response

---

lib/fog/aws/requests/rds/create_db_instance.rb

* in create_db_instance mock request

configure auto_minor_version_upgrade in mock

---

lib/fog/aws/storage.rb

Should fix https://github.com/fog/fog/issues/3544, https://github.com/carrierwaveuploader/carrierwave/issues/1547

Refresh credentials if needed when signing S3 URL

---

lib/fog/aws/requests/rds/create_db_instance.rb

* preferred_maintenance_window
* preferred_backup_window

configure server attributes in mock

---

lib/fog/aws/requests/sns/add_permission.rb
lib/fog/aws/requests/sns/create_topic.rb
lib/fog/aws/requests/sns/remove_permission.rb
lib/fog/aws/sns.rb
tests/requests/sns/topic_tests.rb

mocks for topic permissions

---

lib/fog/aws/compute.rb
lib/fog/aws/parsers/compute/describe_instance_attribute.rb
lib/fog/aws/requests/compute/describe_instance_attribute.rb
tests/requests/compute/instance_attrib_tests.rb

Added request and parser for DescribeInstanceAttribute API

Added a new request - describe_instance_attribute

---

lib/fog/aws/requests/compute/allocate_address.rb
tests/requests/compute/address_tests.rb

raise correct error when exceeding address limit

---

lib/fog/aws/models/compute/flavors.rb

* [announcement](https://aws.amazon.com/blogs/aws/new-t2-large-instances/?sc_campaign=launch&sc_category=ec2&sc_channel=SM&sc_content=t2_large_1&sc_detail=std&sc_medium=aws&sc_publisher=tw&adbsc=social_launches_20150617_47668156&adbid=611079737587269632&adbpl=tw&adbpr=66780587)

add t2.large

---

lib/fog/aws/lambda.rb

I noticed a bug in some AWS Lambda requests. That API allows you to invoke functions by specifying the function id in several ways:
1. plain_function_name
2. account_id:function_name
3. arn:aws:lambda:region:account_id:function:function_name
I noticed I forgot to escape function names for cases 2 and 3. This PR fixes that.
Thanks,

Escape Lambda function name in request paths

---

lib/fog/aws/parsers/compute/describe_route_tables.rb
lib/fog/aws/requests/compute/describe_route_tables.rb
tests/requests/compute/route_tests.rb

Fill in this missing element of the return tuple.
Also CCing @gregburek who is interested in this patch.

Describe vpcPeeringConnectionId

---

lib/fog/aws/requests/dns/change_resource_record_sets.rb
tests/helpers/mock_helper.rb
tests/requests/dns/change_resource_record_sets_tests.rb
tests/requests/emr/helper.rb

fix #change_resource_record_sets

---

lib/fog/aws/auto_scaling.rb
lib/fog/aws/models/auto_scaling/group.rb
lib/fog/aws/requests/auto_scaling/attach_load_balancers.rb
lib/fog/aws/requests/auto_scaling/detach_load_balancers.rb
tests/requests/auto_scaling/auto_scaling_tests.rb

Hey there! Adding some support for these new Auto Scaling API methods:
http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_AttachLoadBalancers.html
http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_DetachLoadBalancers.html
Thanks!

AutoScaling attach/detach ELB support + tests

---

lib/fog/aws/models/rds/server.rb
lib/fog/aws/requests/rds/describe_db_instances.rb
lib/fog/aws/requests/rds/describe_db_snapshots.rb
lib/fog/aws/requests/rds/promote_read_replica.rb
tests/models/rds/server_tests.rb

* use state "modifying"
* alias #promote to #promote_read_replica
* raise correct error when attempting to promote a master server

update #promote_read_replica mock

---

lib/fog/aws/models/compute/volume.rb
lib/fog/aws/parsers/compute/create_volume.rb
lib/fog/aws/parsers/compute/describe_volumes.rb
lib/fog/aws/requests/compute/create_volume.rb
tests/requests/compute/volume_tests.rb

volume#key_id and encrypted tests

---

lib/fog/aws/requests/storage/put_bucket_notification.rb

Fixes what is probably a bad copy paste in code, so the put bucket notification xml verified and constructed correctly.

storage request bad xml schema for put bucket notification fix

---

lib/fog/aws/rds.rb
lib/fog/aws/requests/rds/create_db_instance.rb

* availability_zone cannot be specified when multi_az
in create_db_instance request mock

raise InvalidParameterCombination error

---

lib/fog/aws/requests/rds/modify_db_instance.rb

* to properly update db instance mock

format security groups when modifying db instance

---

lib/fog/aws/iam/paged_collection.rb
lib/fog/aws/models/iam/roles.rb
lib/fog/aws/requests/iam/create_role.rb
lib/fog/aws/requests/iam/get_role.rb
lib/fog/aws/requests/iam/list_roles.rb
tests/models/iam/roles_tests.rb

add IAM role paging

---

lib/fog/aws.rb
lib/fog/aws/version.rb

Really old app started blowing up. I think the new region is legit.

Add new aws regions

---

Gemfile
lib/fog/aws.rb
lib/fog/aws/requests/compute/describe_availability_zones.rb

ap-northeast-2 was missing from Mock#describe_availability_zones.

Added ap-northeast-2 to the fog mocks.

---

lib/fog/aws/models/rds/parameters.rb
lib/fog/aws/parsers/rds/db_parameter_parser.rb
lib/fog/aws/parsers/rds/describe_engine_default_parameters.rb
lib/fog/aws/rds.rb
lib/fog/aws/requests/rds/create_db_instance.rb
lib/fog/aws/requests/rds/describe_db_parameters.rb
lib/fog/aws/requests/rds/describe_engine_default_parameters.rb
lib/fog/aws/requests/rds/modify_db_parameter_group.rb
tests/requests/rds/parameter_group_tests.rb
tests/requests/rds/parameter_request_tests.rb

* default engine parameters
* mocks around parameter groups

rds enhancements

---

lib/fog/aws/requests/compute/describe_availability_zones.rb

Appears to be a copy pasta error.

Correct default DescribeAvailabilityZone filter to zone-name

---

lib/fog/aws/iam.rb
lib/fog/aws/parsers/iam/list_policy_versions.rb
lib/fog/aws/requests/iam/create_policy_version.rb
lib/fog/aws/requests/iam/delete_policy_version.rb
lib/fog/aws/requests/iam/list_attached_role_policies.rb
lib/fog/aws/requests/iam/list_policy_versions.rb
lib/fog/aws/requests/iam/set_default_policy_version.rb
lib/fog/aws/requests/iam/update_assume_role_policy.rb
tests/requests/iam/managed_policy_tests.rb
tests/requests/iam/versioned_managed_policy_tests.rb

Adding:
* Create/Delete Policy Versions
* Set Default Policy Version
* Add Update Assume Role Policy
For functionality request https://github.com/fog/fog-aws/issues/272

Expanding IAM support

---

fog-aws.gemspec

So here's a trivial update for the gemspec's homepage.

GitHub does no longer provide http:// pages

---

lib/fog/aws/requests/cloud_formation/create_stack.rb
lib/fog/aws/requests/cloud_formation/update_stack.rb

Some additional parameters I missed for CreateStack and UpdateStack

Cloud Formation: additional parameters

---

lib/fog/aws.rb
lib/fog/aws/models/support/flagged_resource.rb
lib/fog/aws/models/support/flagged_resources.rb
lib/fog/aws/models/support/trusted_advisor_check.rb
lib/fog/aws/models/support/trusted_advisor_checks.rb
lib/fog/aws/requests/support/describe_trusted_advisor_check_result.rb
lib/fog/aws/requests/support/describe_trusted_advisor_checks.rb
lib/fog/aws/support.rb
tests/models/support/trusted_advisor_tests.rb
tests/requests/support/helper.rb
tests/requests/support/trusted_advisor_check_tests.rb

[AWS Support API Reference](http://docs.aws.amazon.com/awssupport/latest/APIReference/Welcome.html)

add support endpoint and models/requests for trusted advisor checks

---

lib/fog/aws.rb
lib/fog/aws/requests/compute/describe_availability_zones.rb

+ Added region 'us-east-2' ohio
+ Added Az's 
- us-east-2a
- us-east-2b
- us-east-2c

Ohio region

---

lib/fog/aws/models/auto_scaling/group.rb
lib/fog/aws/parsers/auto_scaling/describe_auto_scaling_groups.rb
lib/fog/aws/requests/auto_scaling/create_auto_scaling_group.rb
tests/requests/auto_scaling/helper.rb

This adds support for targetGroups on AutoScalingGroups which is a fix for issue #308

Support for target groups (fix for #308)

---

lib/fog/aws/parsers/cloud_formation/describe_change_set.rb
lib/fog/aws/requests/cloud_formation/create_change_set.rb

This PR solves the following:
1. Get the status of cloudformation change set creation
2. Create change set for stacks that changes IAM roles/policies

Fixed some missing parts in change sets

---

lib/fog/aws/storage.rb

I'm using minio server on development environment, and catch this case using pre-signed url.
But i'm not find way to test this case.

fix host header with another port on s3

---

lib/fog/aws.rb
lib/fog/aws/requests/compute/describe_availability_zones.rb

@geemus this supersedes @chanakyacool PR https://github.com/fog/fog-aws/pull/331 with the us-east-2 back in and less cruft i.e. just the two commits needed.

Canada and London regions

---

lib/fog/aws/parsers/compute/describe_route_tables.rb
lib/fog/aws/requests/compute/describe_route_tables.rb
tests/requests/compute/route_tests.rb

I would like to see natGatewayId when I do describe_route_tables.

add natGatewayId to describe_route_tables

---

lib/fog/aws/models/storage/file.rb

Add missing 'self' to call setter method

Fix multipart upload

---

lib/fog/aws/models/storage/file.rb

Matches to https://github.com/fog/fog/blob/master/lib/fog/internet_archive/models/storage/file.rb

Add check for self.etag before running gsub

---

lib/fog/aws/parsers/storage/get_bucket.rb

not sure how to test this, so no tests were added.

fix https://github.com/fog/fog-aws/issues/369

---

CHANGELOG.md

Generated using https://github.com/skywinder/Github-Changelog-Generator.

Update changelog for 1.4.0

---

tests/models/elasticache/subnet_groups_tests.rb
tests/models/storage/versions_tests.rb
tests/requests/dns/dns_tests.rb
tests/requests/iam/managed_policy_tests.rb
tests/requests/iam/versioned_managed_policy_tests.rb
tests/requests/storage/object_tests.rb

fix(Tests):Remove debugging

---

CONTRIBUTORS.md

Just a plan `git log --pretty="* %cn <%ce>" | sort | uniq`
cc/ @lanej

feat(CONTRIBUTORS): Update

---

.travis.yml
fog-aws.gemspec

This is currently breaking all of our builds.
References https://github.com/bundler/bundler/pull/3559

bundler ~> 1.15

---

lib/fog/aws/models/compute/flavors.rb
lib/fog/aws/requests/compute/run_instances.rb

Hello guys, just a little PR for adding t2.nano instance type (https://aws.amazon.com/fr/ec2/instance-types/ / https://aws.amazon.com/fr/blogs/aws/ec2-update-t2-nano-instances-now-available/).
Thanks.

Add t2.micro in flavors list

---

lib/fog/aws/credential_fetcher.rb

Avoid creating connection if region is not nil

---

lib/fog/aws.rb
lib/fog/aws/requests/compute/describe_availability_zones.rb

Signed-off-by: Laurent Vallar <val@zbla.net>

add france (eu-west-3) new region, fix #424

---

lib/fog/aws/requests/storage/delete_object_url.rb
lib/fog/aws/storage.rb

This PR allows getting pre-signed URLs for deleting objects.

Expose S3 pre-signed object delete url

---

lib/fog/aws/models/compute/flavors.rb

@lanej 
Adding some new instance types.

Add c5 and m5 instance types.

---

lib/fog/aws/models/compute/flavors.rb

Hi !
I'm just adding some new flavors, based on both : 
https://aws.amazon.com/ec2/instance-types/g3/
and
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html#ebs-optimization-support
Thx !

Adding g3 flavors

---

CHANGELOG.md

Congrats on the 3.0.0 release!
I tried to organize this changelog entry to make upgrading easier for users. I think that's the main purpose of a changelog. E.g. I'm upgrading and I want to know what changed. Usually, I don't care what was added or fixed, I just want to know if there are breaking changes. I hope you like this format, it's worked really well for me on my projects.

Docs: Update changelog for 3.0.0

---

lib/fog/aws/models/compute/address.rb
lib/fog/aws/parsers/compute/describe_addresses.rb

Modify describe_address for setting the tags for address

add tags for describe address 

---

lib/fog/aws/requests/dns/change_resource_record_sets.rb

https://github.com/fog/fog-aws/issues/477

pull request in attempt at fix for undefined method issue mentioned in fog/fog-aws#477

---

lib/fog/aws/storage.rb

This PR adds support for Amazon S3 Transfer Acceleration
https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/
https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

Add support for S3 transfer acceleration

---

lib/fog/aws/storage.rb

Right now fog-aws will disable streaming for both multipart and PUT object transfers. However, Oracle Cloud appears to handle streaming fine in the multipart upload case; it's just the single PUT object case where it fails.

WIP: Make S3 Signature v4 streaming optional

---

.gitignore
lib/fog/aws/models/storage/file.rb
lib/fog/aws/parsers/storage/get_object_tagging.rb
lib/fog/aws/requests/storage/get_object_tagging.rb
lib/fog/aws/requests/storage/put_object_tagging.rb
lib/fog/aws/storage.rb

What is done:
- I added the `tags` attribute to the `Storage::File` model, so at creation time we can set the Object tags.
- I added the `get_object_tagging` and `put_object_tagging` requests to the `Storage`.
This PR partially solves #377.

Add object tagging

---

lib/fog/aws/elasticache.rb

Add all regions specified in https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/RegionsAndAZs.html#SupportedRegions

Update elasticache mocking regions

---

lib/fog/aws/parsers/sts/assume_role_with_web_identity.rb

Fixes type in class name for STS assume_role_with_web_identity parser

---

lib/fog/aws.rb

Add South Africa (Cape Town) Region

---

lib/fog/aws.rb

Missing recent region in Milan from regions list

added missing region EU South (Milan)

---

lib/fog/aws/models/compute/flavors.rb

See https://aws.amazon.com/ec2/instance-types/ to review the details

Add all m6gd, r6g, r6gd, c6g, and c6gd instance classes

---

lib/fog/aws/requests/storage/delete_multiple_objects.rb
tests/requests/storage/versioning_tests.rb

This PR is fix for issue describe in #598 . Now bulk/multiple delete can handle multiple versions of single object as well in delete 
request. The solution is as discussed in the issue where options hash accepts versions as an array of strings for a object. The PR is backward compatible to support hash with versions as string only.
Thanks for your time.

Handle multiple versions of objects in multiple delete request

---

lib/fog/aws/models/storage/file.rb
lib/fog/aws/storage.rb

Amazon S3 limits max chunk size that can be uploaded/copied in a single request to 5GB.
Other S3-compatible storages (like, Ceph) do not have such limit.
Ceph shows much better performance when file is copied as a whole, in a single request.
This commit adds `max_put_chunk_size`/`max_copy_chunk_size`storage options
that allow user to configure respective chunk sizes.
Usage of non-positive value will tell fog-aws to use a single put/copy request regardless of file size.
This commit preserves backward compatibility:
if user explicitly sets `multipart_chunk_size` on a `Fog::AWS::Storage::File` instance,
that value will take precedence.

Add storage option to configure multipart put/copy

---

lib/fog/aws/credential_fetcher.rb
tests/credentials_tests.rb

This pull request is based off https://github.com/fog/fog-aws/pull/605/files and cleans up and fixes the implementation and test cases.

 Add support for regional STS endpoints

---

README.md
lib/fog/aws/models/storage/directories.rb

In reference to https://github.com/fog/fog-aws/issues/633
Yard screen shots

Add warning messages around directories.get

---

README.md

Add an example to get a download URL.

Update README file with download url example

---

README.md

Update Readme.md for proper usage of IAM auth

---

lib/fog/aws/storage.rb

closes https://github.com/fog/fog-aws/issues/674

configure connection_options to improve s3 retry

---

lib/fog/aws/models/compute/flavors.rb

Please check the instance information at  - https://aws.amazon.com/ec2/instance-types/

add c6a, c6i, c6id, m6a,m6i, m6id, and r6a, r6i, r6id support

---

CHANGELOG.md

This PR just removes redundant an open bracket.

Fix broken format in CHANGELOG

---

.github/workflows/ruby.yml

Add Ruby 3.3 to CI matrix

---

lib/fog/aws/requests/storage/copy_object.rb

mark copy_object as idempotent

---

lib/fog/aws/requests/storage/post_object_restore.rb
tests/requests/storage/object_tests.rb

Add ability to specify s3 restore object tier in post_object_restore
